### DISCUSSION TITLE
Image for User Preset Playlists

### DISCUSSION THREAD

**Discussion by m4tthall73** [thlucas1/spotifyplus_card#25] [General]
Hi,

I have been starting to set-up the card with some user presets that provide convenient access to my favourite playlists. This seems to work fine but wondering if it is possible to have the playlist image from spotify rather than link to an image file? I am assuming not, as I am sure this would have been an option you'd have started with but thought I should ask just in case.

Thanks for your work on this, it's much appreciated.

```
userPresets:
  - name: Discover Weekly
    subtitle: Various Artists
    image_url: >-
      https://dailymix-images.scdn.co/v2/img/ab6761610000e5ebcd3f796bd7ea49ed7615a550/1/en/default 
    uri: spotify:playlist:37i9dQZEVXcJTzKEkDXCQB
    type: playlist
```

**Comment by thlucas1** [comment]
@m4tthall73 
Hi Matt - Unfortunately, that is not possible since the presets are defined via code (e.g. no UI editor).  By design, these are meant to be entered as a "one-time" setup kind of thing and not really touched after that (unless you delete them).  Hence not a lot of effort on my part went into maintaining them.

The playlist image can easily be obtained via the [Spotify Web API Get Playlist](https://developer.spotify.com/documentation/web-api/reference/get-playlist) endpoint (see form screenshot example below).  Just enter the playlist ID value and press the "Try It" button.  This will return a bunch of meta data for the playlist, of which the "images" collection has the link(s) to the cover art.  The only problem with this is that the Spotify image link(s) are hosted by a CDN provider, which means that they could potentially change.  This does not happen very often, but is a possibility.

For example, the "Discover Weekly" playlist id is `37i9dQZEVXcJTzKEkDXCQB`, and the image for it is `https://newjams-images.scdn.co/image/ab676477000033ad/dt/v3/discover-weekly/aAbca4VNfzWuUCQ_FGiEFA==/bmVuZW5lbmVuZW5lbmVuZQ==`.  

_Spotify Web API Get Playlist screenshot example_
![image](https://github.com/user-attachments/assets/b17257e7-babd-4385-8298-441c1af6d5ce)

Another idea would be to add an action menu item to "Copy Playlist Image URL to clipboard", which would allow you to easily grab the image url via the search UI.  I can have that added in the next release.

**Comment by thlucas1** [comment]
@m4tthall73 
Hi Matt - I just released the v1.0.12 of the [SpotifyPlus Card](https://community.home-assistant.io/t/spotifyplus-card-dashboard/795290) that helps with the user-preset issue that you mentioned.  I created a new action menu item for each content type (artist, album, track, playlist, podcast, audiobook) that allows you to "Copy Playlist Preset Info to Clipboard"

![image](https://github.com/user-attachments/assets/bf572859-e3f8-484f-87a2-87ad73d7ea89)

When clicked, it formats a userPreset entry and stores it on the clipboard; the contents can then be pasted into the code editor under the `userPresets:` configuration key.  Here's what the clipboard contents look like for the screen capture above:
```
  - name: Seventh Day Slumber
    subtitle: playlist
    image_url: https://i.scdn.co/image/ab67616d0000b2734bfd0e91bf806bc73d736cfd
    uri: spotify:playlist:6G3tdA7sE2LVUzgZtj1Z2R
    type: playlist
```

I am trying to find a way to automatically update the configuration when the menu-item is clicked (rather than the copy / paste clipboard route), but there have been some difficulties doing that.  I haven't given up on it, but it's going to take some time and thought to get it to work I think.

Anyway, thought you would want to know.

**Comment by thlucas1** [comment]
@m4tthall73 
Hi Matt - I found a way to programmatically add Spotify media items to the SpotifyPlus Card User Presets section.  I just released the v1.0.44 of the [SpotifyPlus Card](https://github.com/thlucas1/spotifyplus_card/wiki) that adds this functionality. I created a new action menu item for each content type (artist, album, track, playlist, podcast, audiobook, etc) that allows you to "Add <media type> to User Presets".

![image](https://github.com/user-attachments/assets/01ebd1a1-eeb0-4d5b-ae23-fd8fa1885d32)

This will create a new preset item in the `userPresets` collection of the card configuration:
```
type: custom:spotifyplus-card
cardUniqueId: 1de2a826-b92b-4528-9b37-a5654ab5abe8
...
userPresets:
  - name: Seventh Day Slumber Playlist
    image_url: https://mosaic.scdn.co/640/ab67616d00001e023d82a4f6b0a3d4fe2bc5e519ab67616d00001e024bfd0e91bf806bc73d736cfdab67616d00001e02749d0c1c307bb6a1601763faab67616d00001e02a4dc2e03e08a5b22867f6940
    subtitle: playlist
    type: playlist
    uri: spotify:playlist:1WvMpm9arn8hzpFj5Qny61
```

Note that shared JSON User Preset items must still be added / removed manually via a file editor.  The above functionality only updates the individual card configuration user preset items.

### Requirements
Note that you must have the [`cardUniqueId` option](https://github.com/thlucas1/spotifyplus_card/wiki/Configuration-Options#carduniqueid) defined in the card configuration in order to use the new functionality.  The `cardUniqueId` option contains the unique ID of the card; this value is used to find the specific card entry in a lovelace storage file, so that it can be updated programmatically (no editor) if need be.

As of v1.0.44, any new card instances created via the card picker will generate a UUID value for this option; card instances created prior to v1.0.44 must have a value manually assigned. The value can be any type of string (a UUID format is suggested), but it HAS to be unique!

__Caution__

You must ensure that no two values are alike amongst card instances that are defined on the same dashboard! Failure to do so will result in cards being overlaid during editor-less configuration option changes.

YAML Example
```
cardUniqueId: 1de2a826-b92b-4528-9b37-a5654ab5abe8
```

Just thought you would want to know.
